name: 'Cancel this build'
description: 'Uses the GitHub Actions API to cancel the build'
inputs:
  token:
    description: 'Token'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'cancel.js'
branding:
  icon: 'cloud-snow'
  color: 'orange'
